name: sqflite_common_test
description: SQFlite test package
version: 0.3.1
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sqflite_common: '>=1.0.1-dev.1'
  process_run:

dev_dependencies:
  test:
  pedantic:
  sqflite_common_ffi:
    path: ../sqflite_common_ffi

dependency_overrides:
  pedantic: '>=1.9.0'
  sqflite_common:
    path: ../sqflite_common
